name: rotating_widget_test
description: Example code to test package rotating_widgets 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rotating_widgets:
    path: D:\packages\rotating_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true