name: rotating_widgets
description: Flutter Package to build rotating widgets with customizable option to allow rotation across X Axis,Y Axis and change the angle(radian) by which rotation occurs.
version: 1.1.1
homepage: https://github.com/Hardikb19/rotating-widgets

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: