name: rotating_widgets
description: Highly customizable Flutter Package to allow user to convert any widget into a 3D rotate-able widget
version: 1.2.0
homepage: https://github.com/Hardikb19/rotating-widgets

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: